ci: add build docker image

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -24,9 +24,23 @@ jobs:
     - name: Build with Maven
       run: mvn -B -V -DskipTests=false verify
 
-    - name: Upload test results
-      if: always()
-      uses: actions/upload-artifact@v4
-      with:
-        name: test-results
-        path: target/surefire-reports || target/failsafe-reports || target
+    #- name: Upload test results
+    #  if: always()
+    #  uses: actions/upload-artifact@v4
+    #  with:
+    #    name: test-results
+    #    path: |
+    #      target/surefire-reports/**/*.xml
+    #      target/failsafe-reports/**/*.xml
+    #      target/**
+    #    if-no-files-found: warn
+
+    - name: Copy JAR to docker context
+      run: |
+        mkdir -p dockerfile
+        echo "Jar files in target:"
+        ls -la target/*.jar || true
+        cp target/*.jar dockerfile/ || true
+
+    - name: Build Docker image
+      run: docker build -f dockerfile/Dockerfile -t my-app-image:${{ github.sha }} dockerfile/
